In [ ]:
#pip install numpy==1.8

In [3]:
import pandas as pd
#import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#Model selection and model
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

#Evaluation Metrics
from sklearn.metrics import mean_squared_error     
from sklearn import metrics

import warnings
warnings.filterwarnings("ignore")

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\Users\HP\anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\HP\anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\HP\anaconda3\lib\site-packages\ipykernel_launcher.py", line 17, in <module>
    app.launch_new_instance()
  File "C:\Users\HP\anaconda3\lib\site-packages\traitlets\config\application.py", line 1075, in launch_instance
    app.start()
  File "C:\Users\HP\anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 701, in start
    self.io_loop.start()
  File "C:\Users\HP\anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 205, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\HP\anaconda3\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\HP\anaconda3\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "C:\Users\HP\anaconda3\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "C:\Users\HP\anaconda3\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\HP\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 534, in dispatch_queue
    await self.process_one()
  File "C:\Users\HP\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 523, in process_one
    await dispatch(*args)
  File "C:\Users\HP\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 429, in dispatch_shell
    await result
  File "C:\Users\HP\anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 767, in execute_request
    reply_content = await reply_content
  File "C:\Users\HP\anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 429, in do_execute
    res = shell.run_cell(
  File "C:\Users\HP\anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "C:\Users\HP\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3024, in run_cell
    result = self._run_cell(
  File "C:\Users\HP\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3079, in _run_cell
    result = runner(coro)
  File "C:\Users\HP\anaconda3\lib\site-packages\IPython\core\async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\HP\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3284, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "C:\Users\HP\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3466, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "C:\Users\HP\anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3526, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "C:\Users\Public\Documents\Wondershare\CreatorTemp\ipykernel_9832\3337095836.py", line 3, in <module>
    import matplotlib.pyplot as plt
  File "C:\Users\HP\anaconda3\lib\site-packages\matplotlib\__init__.py", line 109, in <module>
    from . import _api, _version, cbook, docstring, rcsetup
  File "C:\Users\HP\anaconda3\lib\site-packages\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "C:\Users\HP\anaconda3\lib\site-packages\matplotlib\colors.py", line 56, in <module>
    from matplotlib import _api, cbook, scale
  File "C:\Users\HP\anaconda3\lib\site-packages\matplotlib\scale.py", line 23, in <module>
    from matplotlib.ticker import (
  File "C:\Users\HP\anaconda3\lib\site-packages\matplotlib\ticker.py", line 136, in <module>
    from matplotlib import transforms as mtransforms
  File "C:\Users\HP\anaconda3\lib\site-packages\matplotlib\transforms.py", line 46, in <module>
    from matplotlib._path import (

AttributeError: _ARRAY_API not found

ImportError: numpy.core.multiarray failed to import

In [5]:
df = pd.read_csv("Salary_data.csv")
df.head()

   Gender  YearsExperience Location  Salary
0  Female              1.0  Nigeria    32383
1    Male              1.1    Ghana    45207
2    Male              1.3     Togo    39751
3  Female              2.0   Guinea    43525
4  Female              2.2  Burkina    39891

In [ ]:
df.shape

In [ ]:
df.info()

In [ ]:
df.describe()

In [ ]:
df.isnull().sum()

In [ ]:
#plt.figure(figsize = (3,2))
#sns.boxplot(x = df["Gender"])

#plt.show()

In [ ]:
df["Gender"].dtypes

In [ ]:
###df.rename({"Salary ":"Salary"}, inplace = True)

In [7]:
##One Hot Encoding

df = pd.get_dummies(df, columns = ["Gender"], drop_first = True)

In [9]:
df

    YearsExperience Location  Salary   Gender_Male
0               1.0  Nigeria    32383        False
1               1.1    Ghana    45207         True
2               1.3     Togo    39751         True
3               2.0   Guinea    43525        False
4               2.2  Burkina    39891        False
5               2.7     Togo    56642         True
6               3.0    Ghana    60150         True
7               3.2   Garbon    54445        False
8               3.2  Nigeria    64445        False
9               3.7    Benin    57189         True
10              3.9       SA    63218        False
11              4.0    Benin    55794         True
12              4.0    Ghana    56957         True
13              4.1       SA    57081        False

In [11]:
df["Gender_Male"]= df["Gender_Male"].astype("int64")

In [13]:
df

    YearsExperience Location  Salary   Gender_Male
0               1.0  Nigeria    32383            0
1               1.1    Ghana    45207            1
2               1.3     Togo    39751            1
3               2.0   Guinea    43525            0
4               2.2  Burkina    39891            0
5               2.7     Togo    56642            1
6               3.0    Ghana    60150            1
7               3.2   Garbon    54445            0
8               3.2  Nigeria    64445            0
9               3.7    Benin    57189            1
10              3.9       SA    63218            0
11              4.0    Benin    55794            1
12              4.0    Ghana    56957            1
13              4.1       SA    57081            0

In [15]:
df['Location'].nunique()

8

In [27]:
df = df.select_dtypes(exclude = object)
df

    YearsExperience  Salary   Gender_Male
0               1.0    32383            0
1               1.1    45207            1
2               1.3    39751            1
3               2.0    43525            0
4               2.2    39891            0
5               2.7    56642            1
6               3.0    60150            1
7               3.2    54445            0
8               3.2    64445            0
9               3.7    57189            1
10              3.9    63218            0
11              4.0    55794            1
12              4.0    56957            1
13              4.1    57081            0

In [23]:
#sns.heatmap(df.corr(), annot = True )

In [31]:
df.head()

   YearsExperience  Salary   Gender_Male
0              1.0    32383            0
1              1.1    45207            1
2              1.3    39751            1
3              2.0    43525            0
4              2.2    39891            0

In [39]:
df.columns

Index(['YearsExperience', 'Salary ', 'Gender_Male'], dtype='object')

In [43]:
y = df["Salary "]

In [51]:
x = df[['YearsExperience', 'Gender_Male']]
x

    YearsExperience  Gender_Male
0               1.0            0
1               1.1            1
2               1.3            1
3               2.0            0
4               2.2            0
5               2.7            1
6               3.0            1
7               3.2            0
8               3.2            0
9               3.7            1
10              3.9            0
11              4.0            1
12              4.0            1
13              4.1            0

In [55]:
#Model selection and model
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [57]:
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size= 0.3,random_state= 1)

In [59]:
y_test

3     43525
7     54445
6     60150
2     39751
10    63218
Name: Salary , dtype: int64

In [21]:
x_train = pd.DataFrame(x_train)
x_test = pd.DataFrame(x_test)

In [22]:
x_test

    YearsExperience
3               2.0
7               3.2
6               3.0
2               1.3
10              3.9

In [61]:
model = LinearRegression()   #build linear regression model (Intialistiate)
model
model.fit(x_train,y_train)   #### ML to learn

LinearRegression()

In [63]:
Pred = model.predict(x_test)

Pred

array([44395.45454545, 52180.18181818, 53709.07272727, 42680.70909091,
       56721.27272727])

In [65]:
#Evaluation Metrics
from sklearn.metrics import mean_squared_error     
from sklearn import metrics

import warnings
warnings.filterwarnings("ignore")

In [67]:
plt.scatter(x,y, color = "red")
plt.plot(x_test,Pred, color = "black")
plt.title("Linear Regression of Years of Exp and Salary")
plt.xlabel ("Years of Exp")
plt.ylabel ("Salary")

plt.show()

NameError: name 'plt' is not defined

In [69]:
print("MSE", mean_squared_error(y_test,Pred))
print("R squared", metrics.r2_score(y_test,Pred))

MSE 19632659.451702464
R squared 0.7662057719953671

In [28]:
intercept = model.intercept_
slope = model.coef_

In [30]:
intercept

32271.01670998886

In [32]:
slope

array([6736.53267731])

In [71]:
import pickle

In [73]:
with open ("final_model.pkl","wb") as file:
    pickle.dump(model,file)